<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\MediaForgePS\MediaForgePS.csproj" />
    <ProjectReference Include="..\MediaForgePS.ComponentTests\MediaForgePS.ComponentTests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\MediaForgePS.ComponentTests\TestAssets\**\*.*">
      <Link>TestAssets\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
